import Config from 'react-native-config';

export const ENVConfig = {
  APP_ENV: Config.ENV,
  API_URL: Config.API_URL,
  APP_DISPLAY_NAME: Config.APP_NAME,
  IOS_APP_VERSION_CODE: Config.IOS_APP_VERSION_CODE,
  IOS_APP_BUILD_CODE: Config.IOS_APP_BUILD_CODE,
  IOS_APP_ID: Config.IOS_APP_ID,
  ANDROID_APP_VERSION_CODE: Config.ANDROID_APP_VERSION_CODE,
  ANDROID_APP_BUILD_CODE: Config.ANDROID_APP_BUILD_CODE,
  ANDROID_APP_ID: Config.ANDROID_APP_ID,
  DEFAULT_FALLBACK_LNG_I18n: Config.DEFAULT_FALLBACK_LNG_I18n,
  STORAGE_APP_KEY: Config.STORAGE_APP_KEY,
};
